name = input("Enter ur name : ")
city = input("Enter ur city :")
fav_food = input("Enter ur fav food :")
Movies = input("Enter ur fav movies :")
car = input("Enter ur city : ")
heroien = input("Enter your fav heroin :")
hero = input("Enter ur fav hero :")
Hobby = input("Enter ur hobby :")
Fav_sports = input("fav sportsperson :")
Fav_dog = input("Enter ur dog breed :")

print("!!!INFO!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{Movies=}')
print(f'{car=}')
print(f'{heroien=}')
print(f'{hero=}')
print(f'{Hobby=}')
print(f'{Fav_sports=}')
print(f'{Fav_dog=}')

